# 文件上传配置

lin:
  file:
    # 文件服务域名
    # 如果公共读文件服务器所在域名与前端相同，只写"/"即可，否则写完整域名，如"https://example.org/"
    domain: /
    # 排除文件类型
    exclude:
    # 包括文件类型
    include:
      - JPG
      - PNG
      - JPEG
      - BMP
    # 文件最大数量
    nums: 10
    # 服务器文件路径
    serve-path: assets/**
    # 单个文件最大体积
    single-limit: 100MB
    # 本地文件保存位置
    store-dir: assets/
    # 上传实现
    uploader: local
