#开发环境配置

server:
  # 服务端口
  port: 5000
  servlet:
    context-path: /api
    session:
      cookie:
        name: "CHAKKISESSIONID"
        path: "/"


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "yishiyile"
    url: jdbc:mysql://localhost:3306/chakki-spring?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: "root"

# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    vip.gadfly.chakkispring.mapper: debug
